### ISSUE TITLE
亲,自己不会调用能否在发送一个新版本把,字幕朗读那个功能加上呢.

### ISSUE THREAD

**Issue by KaiTraders** [JuchiaLu/subtitle-speaker#1]
亲,自己不会调用能否在发送一个新版本把,字幕朗读那个功能加上呢.调用微软xiaoxiao

**Comment by JuchiaLu** [comment]
我没记错的话，微软 xiaoxiao 是在线的语音合成，Windows 没有内置，需要联网，且微软没有免费提供
